spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: springcloud-config-icoding-dev

---
spring:
  profiles: tes
  application:
    name: springcloud-config-icoding-test